### ISSUE TITLE
Improve style

### ISSUE THREAD

**Issue by vitobreda** [vitobreda/memory-game#1]
Change style of game to improve the gameplay

**Comment by hyperyuri** [comment]
im working on it

**Comment by hyperyuri** [comment]
Hey!
<a hre="https://github.com/vitobreda/memory-game/pull/2" >MY PR <a/>

**Comment by jeannienguyen** [comment]
Hi @vitobreda, I worked on this as well - PR [here](https://github.com/vitobreda/memory-game/pull/3).
